Requerimientos ST/Models/RequerimientoBuscarModelo.cs
using System;
using System.ComponentModel.DataAnnotations;
namespace Requerimientos_ST.Models
{
    public class RequerimientoBuscarModelo
    {
        [Required]
        [Display(Name = "Identificación")]
        public int Id { get; set; }

        [Required]
        [Display(Name = "Area")]
        public string Area { get; set; }

        [Required]
        [Display(Name = "Aplicativo")]
        public string Aplicativo { get; set; }

        [Required]
        [Display(Name = "Alcance")]
        public string alcance { get; set; }

        [Required]
        [Display(Name = "Prioridad")]
        public string Prioridad { get; set; }

        [Required]
        [Display(Name = "Desarrollador")]
        public string Desarrollador { get; set; }      

        [Display(Name = "Fecha solicitud")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime? FechaSolicitud { get; set; }


        [Display(Name = "Fecha desarrollo")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime? FechaDesarrollo { get; set; }


        [Display(Name = "Fecha prueba")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime? FechaPrueba { get; set; }
    }
}

Requerimientos ST/Models/RequerimientoModelo.cs
using System;
using System.ComponentModel.DataAnnotations;
namespace Requerimientos_ST.Models
{
    public class RequerimientoModelo
    {
        [Required]
        [Display(Name = "Identificación")]
        public int Id { get; set; }

        [Required]
        [Display(Name = "Area")]
        public int? Area { get; set; }

        [Required]
        [Display(Name = "Aplicativo")]
        public int? Aplicativo { get; set; }

        [Required]
        [Display(Name = "Alcance")]
        public string Alcance { get; set; }

        [Required]
        [Display(Name = "Motivo de cambio")]
        public string MotivoCambio { get; set; }

        [Required]
        [Display(Name = "Justifcación")]
        public string Justificacion { get; set; }
        [Required]
        [Display(Name = "Prioridad")]
        public int? Prioridad { get; set; }

        [Required]
        [Display(Name = "Desarrollador")]
        public int? Desarrollador { get; set; }
                
        [Display(Name = "Fecha solicitud")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime? FechaSolicitud { get; set; }
        
        [Display(Name = "Fecha desarrollo")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime? FechaDesarrollo { get; set; }

        [Display(Name = "Nueva Fecha de desarrollo")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime? NuevaFechaDesarrollo { get; set; }

        [Display(Name = "Fecha prueba")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime? FechaPrueba { get; set; }

        public string BtnAccion { get; set; }
    }
}

Requerimientos ST/Controllers/PrincipalController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using Requerimientos_ST.Models;
using Requerimientos_ST.Helpers;

namespace Requerimientos_ST.Controllers
{
    public class PrincipalController : Controller
    {
        // GET: Principal
        public ActionResult Index(int ? IdRequerimiento)
        {
            try
            {
                RequerimientoModelo ModeloRetornar = Funciones.Busqueda(IdRequerimiento);
                return View(ModeloRetornar);
            }
            catch (Exception ex)
            {
                return JavaScript($"alert('Ha ocurrido un error {ex.Message} ');");
            }
       
        }

        public ActionResult InsertarRequerimiento(RequerimientoModelo ModeloTrabajar)
        {
            try
            {
                List<RequerimientoBuscarModelo> ModeloRetornar = Funciones.AccionesRequerimientos(ModeloTrabajar);
                return View(ModeloRetornar);

            }
            catch (Exception ex)
            {
                return JavaScript($"alert('Vuelva a intentarlo{ex.Message}');");
            }
       
        }

        public ActionResult EliminarRequerimiento(int IdRequerimiento)
        {
            try
            {
                List<RequerimientoBuscarModelo> ModeloRetornar = Funciones.EliminarRequerimiento(IdRequerimiento);
                return View("../Principal/InsertarRequerimiento", ModeloRetornar);
            }
            catch (Exception ex)
            {
                return JavaScript($"alert('Ha ocurrido un error {ex.Message } ');");
            }
        }        
    }
}

Requerimientos ST/Views/Principal/Index.cshtml
@model Requerimientos_ST.Models.RequerimientoModelo
@{
    ViewBag.Title = "Index";
    
}
<div>
    <div class="card" style="margin-left:30px;margin-right:30px;margin-top:20px">
        <div class="card-header bg-primary" style="color:white">
            <strong>
                DATOS REQUERIMIENTO
            </strong>
        </div>
        <div class="card-body">
            @using (Ajax.BeginForm("InsertarRequerimiento", "Principal", Model, new AjaxOptions
            {
                LoadingElementId = "progress",
                HttpMethod = "Post",
                InsertionMode = InsertionMode.Replace,
                UpdateTargetId = "IdDivResultado",
            }, new { id ="idFormularioRequerimiento"+ Model.Id }))
            {
                <div class="row justify-content-md-center">
                    @Html.HiddenFor(x => x.Id)
                    <div class="col-sm-4">
                        <div class="form-group col-margin" style="text-align:center">
                            @Html.LabelFor(m => m.Area, new { @class = "control-label" })
                            @Html.DropDownListFor(m => m.Area, Requerimientos_ST.Helpers.Funciones.GetActividadesList(), "Seleccione", new { @class = "form-control", @style = "width:100%;" })

                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group col-margin" style="text-align:center">
                            @Html.LabelFor(m => m.Aplicativo, new { @class = "control-label" })
                            @Html.DropDownListFor(m => m.Aplicativo, Requerimientos_ST.Helpers.Funciones.GetAplicativosList(), "Seleccione", new { @class = "form-control", @style = "width:100%;" })
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group col-margin" style="text-align:center">
                            @Html.LabelFor(m => m.Prioridad, new { @class = "control-label" })
                            @Html.DropDownListFor(m => m.Prioridad, Requerimientos_ST.Helpers.Funciones.GetPrioridadesList(), "Seleccione", new { @class = "form-control",  @style = "width:100%;" })
                        </div>
                    </div>
                </div>
                <div class="row justify-content-md-center">
                    <div class="col-sm-4">
                        <div class="form-group col-margin" style="text-align:center">
                            @Html.LabelFor(m => m.Alcance, new { @class = "control-label" })
                            @Html.TextBoxFor(m => m.Alcance, new { placeholder = "Alcance", @class = "form-control" })
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group col-margin" style="text-align:center">
                            @Html.LabelFor(m => m.Desarrollador, new { @class = "control-label" })
                            @Html.DropDownListFor(m => m.Desarrollador, Requerimientos_ST.Helpers.Funciones.GetDesarrolladoresList(), "Seleccione", new { @class = "form-control", @style = "width:100%;" })

                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group col-margin" style="text-align:center">
                            @Html.LabelFor(m => m.FechaSolicitud, new { @class = "control-label" })                     
                            @Html.TextBoxFor(m => m.FechaSolicitud, "", new { placeholder = "Fecha solicitud", @class = "form-control datepicker" })
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-4">
                        <div class="form-group col-margin" style="text-align:center">
                            @Html.LabelFor(m => m.FechaDesarrollo, new { @class = "control-label" })
                            @Html.TextBoxFor(m => m.FechaDesarrollo, "", new { placeholder = "Fecha desarrollo", @class = "form-control datepicker"  })
                        </div>
                    </div>
                    @if (Model.Id > 0)
                    {
                        <div class="col-sm-4">
                            <div class="form-group col-margin" style="text-align:center">
                                @Html.LabelFor(m => m.NuevaFechaDesarrollo, new { @class = "control-label" })
                                @Html.TextBoxFor(m => m.NuevaFechaDesarrollo , "", new { placeholder = "Nueva fecha desarrollo", @class = "form-control datepicker" })
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="form-group col-margin" style="text-align:center">
                                @Html.LabelFor(m => m.MotivoCambio, new { @class = "control-label" })
                                @Html.TextBoxFor(m => m.MotivoCambio, new { placeholder = "MotivoCambio", @class = "form-control" })
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="form-group col-margin" style="text-align:center">
                                @Html.LabelFor(m => m.Justificacion, new { @class = "control-label" })                                
                                @Html.TextAreaFor(m => m.Justificacion, new {@class = "form-control" })                                 
                            </div>
                        </div>
                    }
                </div>
                <div class="row">
                    @if (Model.Id == 0)
                    {
                    <div class="col-sm-4">
                        <div class="form-actions" style="margin-bottom:15px;margin-top:15px;padding-top:15px">
                            <input type="submit" name="btnAccion" id="BTN1_@Model.Id" value="Insertar" style="width:100%" class="btn btn-primary text-white" />
                        </div>
                    </div>
                    }
                    <div class="col-sm-4">
                        <div class="form-actions" style="margin-bottom:15px;margin-top:15px;padding-top:15px">
                            <input type="submit" name="btnAccion" id="BTN2_@Model.Id" value="Buscar" style="width:100%" class="btn btn-primary text-white" />
                        </div>
                    </div>
                  @if(Model.Id > 0)
                  { 
                      <div class="col-sm-4">
                          <div class="form-actions" style="margin-bottom:15px;margin-top:15px;padding-top:15px">
                                <input type="submit" name="btnAccion" id="BTN3_@Model.Id" value="Editar" style="width:100%" from="'idFormularioRequerimiento'+@Model.Id" class="btn btn-primary text-white" />
                          </div>
                      </div>
                    }
                </div>

            }

        </div>
    </div>
    <div id="progress" style="background-image:url(@Url.Content("~/Imagenes/cargando.gif"));width:64px;height:64px;margin-left:auto;margin-right:auto;text-align:center;display:table-cell;vertical-align:middle; display: none;"></div>

    <div class="card border-top" style="margin-left:30px;margin-right:30px;margin-top:20px">
        <div class="card-header bg-light">Resultado de la consulta</div>
        <div class="card-body">
            <div id="IdDivResultado">

            </div>
        </div>
    </div>

    <script>
        $(document).ready(function () {

            $('.datepicker').datepicker({
                format: 'dd/mm/yyyy',
                language: 'es',
                allowInputToggle: true,
                orientation: "bottom left"
            });
        });
        
    </script>
</div>

Requerimientos ST/Views/Principal/InsertarRequerimiento.cshtml
@model List<Requerimientos_ST.Models.RequerimientoBuscarModelo>
@{
    Layout = null;
}
@if (Model.Count > 0)
{

    <table id="TabInfoRequerimiento" class="display" style="width:100%;">
        <thead>
            <tr>

                <th>
                    @Html.LabelFor(x => Model[0].Id)
                </th>
                <th>
                    @Html.LabelFor(x => Model[0].Area)
                </th>
                <th>
                    @Html.LabelFor(x => Model[0].Aplicativo)
                </th>
                <th>
                    @Html.LabelFor(x => Model[0].alcance)
                </th>
                <th>
                    @Html.LabelFor(x => Model[0].FechaSolicitud)
                </th>
                <th>
                    @Html.LabelFor(x => Model[0].Prioridad)
                </th>
                <th>
                    @Html.LabelFor(x => Model[0].Desarrollador)
                </th>
                <th>
                    @Html.LabelFor(x => Model[0].FechaDesarrollo)
                </th>
                <th>
                    @Html.LabelFor(x => Model[0].FechaPrueba)
                </th>
                <th align="center">
                    Eliminar
                </th>
                <th align="center">
                    Selecionar
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>

                    <td>
                        @Html.DisplayFor(x => item.Id)
                    </td>
                    <td>
                        @Html.DisplayFor(x => item.Area)
                    </td>
                    <td>
                        @Html.DisplayFor(x => item.Aplicativo)
                    </td>
                    <td>
                        @Html.DisplayFor(x => item.alcance)
                    </td>
                    <td>
                        @Html.DisplayFor(x => item.FechaSolicitud)
                    </td>
                    <td>
                        @Html.DisplayFor(x => item.Prioridad)
                    </td>
                    <td>
                        @Html.DisplayFor(x => item.Desarrollador)
                    </td>
                    <td>
                        @Html.DisplayFor(x => item.FechaDesarrollo)
                    </td>
                    <td>
                        @Html.DisplayFor(x => item.FechaPrueba)
                    </td>

                    <td>
                        @using (Ajax.BeginForm("EliminarRequerimiento", "Principal", new { IdRequerimiento = item.Id }, new AjaxOptions
                        {
                            LoadingElementId = "progress",
                            HttpMethod = "Post",
                            InsertionMode = InsertionMode.Replace,
                            UpdateTargetId = "IdDivResultado",
                        }, new { id = "idFormularioRewuerimientoBusqueda" }))
                        {
                            // de esta pantalla quiero refrecar la pantalla que llama esta

                            <button class="btn btn-sm btn-outline-info" type="submit">
                                <span class="glyphicon glyphicon-edit"></span>
                                <strong>Eliminar</strong>
                            </button>
                        }
                    </td>
                    <td>

                        @using (Html.BeginForm("Index", "Principal", new { IdRequerimiento = item.Id }, FormMethod.Post, new { id = "idFormularioRequerimientoSeleccionar_" + item.Id }))
                        {
                            <button class="btn btn-sm btn-outline-info" form="idFormularioRequerimientoSeleccionar_@item.Id" type="submit" @*onclick="prueba(@item.Id)"*@>
                                <span class="glyphicon glyphicon-edit"></span>
                                <strong>Seleccionar</strong>
                            </button>
                        }



                    </td>
                </tr>
            }
        </tbody>
    </table>

}

<script>
    $(document).ready(function () {
        $('#TabInfoRequerimiento').DataTable({
            responsive: true
        });
    });
   
</script>

Requerimientos ST/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Requerimientos ST</title>

    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />

    <link href="~/Content/layout_estilos.css" rel="stylesheet" />
    <link href="~/Content/jquery-ui-1.10.4.custom.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-datepicker.min.css" rel="stylesheet" />


    <script src="~/Scripts/jquery-3.6.0.min.js"></script>
    <script src="~/Scripts/jquery-ui-1.12.1.js"></script>



    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <script src="~/Scripts/bootstrap-datepicker.min.js"></script>


    <link href="~/Content/DataTables/css/jquery.dataTables.min.css" rel="stylesheet" />
    <link href="~/Content/DataTables/css/buttons.dataTables.min.css" rel="stylesheet" />
    <link href="~/Content/DataTables/css/responsive.dataTables.min.css" rel="stylesheet" />
    <link href="~/Content/DataTables/css/fixedColumns.dataTables.min.css" rel="stylesheet" />


    <script src="~/Scripts/DataTables/jquery.dataTables.min.js"></script>
    <script src="~/Scripts/DataTables/dataTables.buttons.min.js"></script>
    <script src="~/Scripts/DataTables/buttons.html5.min.js"></script>
    <script src="~/Scripts/DataTables/dataTables.responsive.min.js"></script>
    <script src="~/Scripts/DataTables/dataTables.fixedColumns.min.js"></script>
</head>
<body>


    <div class="container body-content" >
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

  
</body>
</html>